env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'airbnb-typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - only-warn
rules:
  eqeqeq: off
  no-underscore-dangle: off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-shadow': off
  '@typescript-eslint/no-redeclare': off
  import/extensions: off
