env:
  browser: true
  es2021: true
extends:
  - airbnb
  - 'airbnb-typescript'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - only-warn
rules:
  eqeqeq: off
  no-underscore-dangle: off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-shadow': off
  '@typescript-eslint/no-redeclare': off
  import/extensions: off
  react/react-in-jsx-scope: off
  import/no-extraneous-dependencies: off
  react/destructuring-assignment: off
  max-len: off
  react/prop-types: off
  react/jsx-props-no-spreading: off
  react/jsx-no-undef: off
  react/require-default-props: off
